version: '3.8'

services:
  brain-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: brain-ai:4.0.0
    container_name: brain-ai-service
    ports:
      - "50051:50051"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - BRAIN_AI_ENV=production
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "brain_ai_demo"]
      interval: 30s
      timeout: 10s
      retries: 3
    resources:
      limits:
        cpus: '4.0'
        memory: 4G
      reservations:
        cpus: '2.0'
        memory: 2G
